// Database types - will be generated by Supabase CLI
// Run: supabase gen types typescript --local > src/lib/supabase/database.types.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type PatientStatus = 'invited' | 'baseline' | 'active' | 'completed' | 'archived'

export interface Database {
  public: {
    Tables: {
      therapists: {
        Row: {
          id: string
          email: string
          name: string
          credentials: string | null
          timezone: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email: string
          name: string
          credentials?: string | null
          timezone?: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          name?: string
          credentials?: string | null
          timezone?: string
          created_at?: string
          updated_at?: string
        }
      }
      patients: {
        Row: {
          id: string
          email: string
          name: string
          therapist_id: string
          timezone: string
          status: PatientStatus
          current_session: number
          baseline_date: string | null
          min_sleep_window: number
          invitation_token: string | null
          invited_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email: string
          name: string
          therapist_id: string
          timezone?: string
          status?: PatientStatus
          current_session?: number
          baseline_date?: string | null
          min_sleep_window?: number
          invitation_token?: string | null
          invited_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          name?: string
          therapist_id?: string
          timezone?: string
          status?: PatientStatus
          current_session?: number
          baseline_date?: string | null
          min_sleep_window?: number
          invitation_token?: string | null
          invited_at?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      prescriptions: {
        Row: {
          id: string
          patient_id: string
          bedtime: string
          wake_time: string
          window_minutes: number
          effective_date: string
          created_by: string
          notes: string | null
          created_at: string
        }
        Insert: {
          id?: string
          patient_id: string
          bedtime: string
          wake_time: string
          window_minutes: number
          effective_date: string
          created_by: string
          notes?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          patient_id?: string
          bedtime?: string
          wake_time?: string
          window_minutes?: number
          effective_date?: string
          created_by?: string
          notes?: string | null
          created_at?: string
        }
      }
      diary_entries: {
        Row: {
          id: string
          patient_id: string
          date: string
          ttb: string
          tts: string
          tfa: string
          tob: string
          sol: number
          sol_out_of_bed: number
          awakenings: number
          waso: number
          waso_out_of_bed: number
          ema: number
          ema_out_of_bed: number
          tib: number | null
          twt: number | null
          twt_out: number | null
          tst: number | null
          se: number | null
          prescribed_bedtime: string | null
          prescribed_wake_time: string | null
          bedtime_deviation: number | null
          waketime_deviation: number | null
          quality_rating: number | null
          notes: string | null
          answers: Json | null
          entered_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          patient_id: string
          date: string
          ttb: string
          tts: string
          tfa: string
          tob: string
          sol?: number
          sol_out_of_bed?: number
          awakenings?: number
          waso?: number
          waso_out_of_bed?: number
          ema?: number
          ema_out_of_bed?: number
          tib?: number | null
          twt?: number | null
          twt_out?: number | null
          tst?: number | null
          se?: number | null
          prescribed_bedtime?: string | null
          prescribed_wake_time?: string | null
          bedtime_deviation?: number | null
          waketime_deviation?: number | null
          quality_rating?: number | null
          notes?: string | null
          answers?: Json | null
          entered_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          patient_id?: string
          date?: string
          ttb?: string
          tts?: string
          tfa?: string
          tob?: string
          sol?: number
          sol_out_of_bed?: number
          awakenings?: number
          waso?: number
          waso_out_of_bed?: number
          ema?: number
          ema_out_of_bed?: number
          tib?: number | null
          twt?: number | null
          twt_out?: number | null
          tst?: number | null
          se?: number | null
          prescribed_bedtime?: string | null
          prescribed_wake_time?: string | null
          bedtime_deviation?: number | null
          waketime_deviation?: number | null
          quality_rating?: number | null
          notes?: string | null
          answers?: Json | null
          entered_by?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      sessions: {
        Row: {
          id: string
          patient_id: string
          therapist_id: string
          session_number: number
          date: string
          prescription_id: string | null
          notes: string | null
          titration_data: Json | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          patient_id: string
          therapist_id: string
          session_number: number
          date: string
          prescription_id?: string | null
          notes?: string | null
          titration_data?: Json | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          patient_id?: string
          therapist_id?: string
          session_number?: number
          date?: string
          prescription_id?: string | null
          notes?: string | null
          titration_data?: Json | null
          created_at?: string
          updated_at?: string
        }
      }
      isi_scores: {
        Row: {
          id: string
          patient_id: string
          session_id: string | null
          date: string
          score: number
          answers: Json
          assessment_type: 'intake' | 'mid_treatment' | 'discharge' | 'follow_up'
          created_at: string
        }
        Insert: {
          id?: string
          patient_id: string
          session_id?: string | null
          date: string
          score: number
          answers: Json
          assessment_type: 'intake' | 'mid_treatment' | 'discharge' | 'follow_up'
          created_at?: string
        }
        Update: {
          id?: string
          patient_id?: string
          session_id?: string | null
          date?: string
          score?: number
          answers?: Json
          assessment_type?: 'intake' | 'mid_treatment' | 'discharge' | 'follow_up'
          created_at?: string
        }
      }
    }
    Functions: {
      check_baseline_establishment: {
        Args: { p_patient_id: string }
        Returns: string | null
      }
      calculate_weekly_averages: {
        Args: { p_patient_id: string; p_end_date?: string }
        Returns: {
          avg_tst: number
          avg_tib: number
          avg_se: number
          avg_sol: number
          avg_waso: number
          avg_ema: number
          avg_twt_out: number
          days_logged: number
        }[]
      }
    }
    Enums: {
      patient_status: PatientStatus
    }
  }
}
